Fix repay borrow
riflending/rlending-ui pull request #101
Opened 2021-01-25 18:06 UTC by fgregoribattista

fix repayBorrow

2021-01-25 20:02 UTC, pmprete requested changes
except my comments looks good

2021-01-25 20:02 UTC, pmprete commented on src/middleware/market.js
> +      const signer = this.token.instance.connect(this.factoryContract.getSigner())
this is the TokenContract plus the signer, use tokenSigner or tokenWithSigner variable name instead to avoid confusion with the signar from getSigner()

2021-01-25 21:04 UTC, fgregoribattista commented on src/components/dialog/repay/RepayInput.vue
> +            .parseUnits(this.maxRepayAllowed)
I was wrong, is parseEther

2021-01-25 21:05 UTC, fgregoribattista commented on src/middleware/market.js
> +      const signer = this.token.instance.connect(this.factoryContract.getSigner())
its ok, is bad name. I fix it

2021-01-25 21:09 UTC, fgregoribattista commented on src/components/dialog/repay/RepayInput.vue
> +            .parseUnits(this.maxRepayAllowed)
done!

2021-01-25 21:09 UTC, fgregoribattista commented on src/middleware/market.js
> +      const signer = this.token.instance.connect(this.factoryContract.getSigner())
done!

2021-01-25 21:28 UTC, galimba submitted a review, later dismissed
LGTM

2021-01-25 21:34 UTC, mariano-aguero approved these changes

2021-01-26 14:41 UTC, pmprete submitted a review, later dismissed
LGTM

2021-01-26 15:13 UTC, galimba approved these changes
LGTM

2021-01-26 15:32 UTC, merged