Improving the dashboard
riflending/rlending-ui pull request #141
Opened 2021-02-15 18:42 UTC by fgregoribattista

fix tweened numbers and add link to rsk swap

2021-02-15 20:18 UTC, pmprete requested changes
Except my comments looks good

2021-02-15 20:18 UTC, pmprete commented on src/styles/_supplyBorrow.scss
> +.rsw-swap-launch{
rename to token-bridge

2021-02-15 20:18 UTC, pmprete commented on src/styles/_supplyBorrow.scss
> +.rsw-swap-launch-logo{
same here

2021-02-15 20:18 UTC, pmprete commented on src/views/MyActivity.vue
> +    <div v-if="dataLaoded" class="upper-banner">
small typo, insteda of dataLaoded should be dataLoaded

2021-02-15 20:18 UTC, pmprete commented on src/views/MyActivity.vue
> +Vue.config.productionTip = false
is this value used?

2021-02-15 20:18 UTC, pmprete commented on src/views/MyActivity.vue
> +      auxiliar: 1,
rename to something more clear please

2021-02-15 20:18 UTC, pmprete commented on src/views/SupplyBorrow.vue
> +        <v-img class="rsw-swap-launch-logo" :src="require(`@/assets/rsk_logo.svg`)" />
use token bridge logo, it can be a jpg instead of a svg

2021-02-15 21:05 UTC, fgregoribattista commented on src/styles/_supplyBorrow.scss
> +.rsw-swap-launch{
Done!

2021-02-15 21:05 UTC, fgregoribattista commented on src/views/MyActivity.vue
> +    <div v-if="dataLaoded" class="upper-banner">
Done!

2021-02-15 21:06 UTC, fgregoribattista commented on src/views/MyActivity.vue
> +Vue.config.productionTip = false
not use, I remove it.

2021-02-15 21:06 UTC, fgregoribattista commented on src/views/MyActivity.vue
> +      auxiliar: 1,
not use, I remove it.

2021-02-15 21:06 UTC, fgregoribattista commented on src/views/SupplyBorrow.vue
> +        <v-img class="rsw-swap-launch-logo" :src="require(`@/assets/rsk_logo.svg`)" />
Done!

2021-02-16 09:32 UTC, pmprete approved these changes
LGTM

2021-02-16 09:32 UTC, merged