fixes factoryContract trying to create contract with undefined address
riflending/rlending-ui pull request #220
Opened 2021-03-08 17:10 UTC by galimba

* This PR fixes the console issue shown below 
![image](https://user-images.githubusercontent.com/5059808/110355454-023c2a80-8018-11eb-99fb-e44de45d678f.png)

2021-03-11 11:48 UTC, pmprete requested changes

2021-03-11 11:48 UTC, pmprete commented on src/middleware/factoryContract.js
> +    console.error(`createContract failed with address:`, address, `abi`, abi)
Instead of console.error use sentry to report the error. Validations are usually the other way around, ask if its not valid, if it's not then thorw a error.
Then at the end after all validations are succesfull return the expected value

2021-03-11 15:01 UTC, mariano-aguero commented on src/middleware/factoryContract.js
> +    console.error(`createContract failed with address:`, address, `abi`, abi)
You can do something like this 
```
if ( !address || !abi || !provider ) {
    Sentry.captureException(new Error('Put your text for the error'))
    // Do something, or the application will crash
    ....
}  else {
   return new ethers.Contract(address, abi, provider)
}
```
the `else` may not be needed if in the `if` the necessary measures are taken...

2021-03-11 20:07 UTC, mariano-aguero approved these changes

2021-03-12 00:43 UTC, pmprete approved these changes
Good Job

2021-03-12 00:43 UTC, merged