fixing the health factor calculations
riflending/rlending-ui pull request #58
Opened 2021-01-08 19:55 UTC by galimba

* Fixes `getHealthFactor` so that it shows a number that corresponds with the equation: `1 - (totalBorrows / (totalSupplied / 2)`
* Removed getHealthFactor from repay modal and used the function declared in Middleware

![image](https://user-images.githubusercontent.com/5059808/104058240-2e7f2a80-51d2-11eb-88eb-8e89af5d799e.png)

2021-01-08 21:14 UTC, galimba commented on src/middleware/middleware.js
> +    // TODO: uncomment the line below to remove hardcoded div 2 value
@mariano-aguero  TODO: after updating `getCollateralFactor()` uncomment the line below and double check that the account health is being accurately calculated. I assumed the collateral factor is 0.5, that's why I hardcoded a division by 2 in this PR.

2021-01-14 21:23 UTC, mariano-aguero commented on src/middleware/middleware.js
> +              const colFactBN = new BigNumber(colFactStr)
We can improve this, is collateralFactora BigNumber ? if not we can create a BigNumber , and use the div operator against the market.factor. This will return a BigNumber

2021-01-14 21:25 UTC, mariano-aguero commented on src/middleware/middleware.js
> +    return Number(new BigNumber(1).minus(numerator.div(denominator)))
Why the `number` ? If you want  to return a Number from this, you need to use `.toNumber()` . Having said that, I prefer the function return a BigNumber so in the view, we can format the BigNumber as we want

2021-01-14 21:26 UTC, mariano-aguero requested changes
See comments

2021-01-15 15:12 UTC, galimba commented on src/middleware/middleware.js
> +              const colFactBN = new BigNumber(colFactStr)
`market.collateralFactorMantissa` is a JS BigNumber and it's operations are incompatible with ethers' BigNumber, so casting couldn't be avoided. A viable alternative would be to use `market.getCollateralFactorMantissa` which is a String, but it would still require casting.

Another issue arises when using `const colFactNum = colFact.toNumber()`, since it overflows.

It was discussed and decided in private that the proposed solution, while inelegant, is functional and does not incur in considerable computational overhead. We included a `TODO` note at the start of the function to keep note of the fact that this should be re-written in the future, but it will most likely require a general refactoring of the code to unify the usage of a single BigNumber library.

2021-01-15 15:12 UTC, galimba commented on src/middleware/middleware.js
> +    return Number(new BigNumber(1).minus(numerator.div(denominator)))
fixed in the next push

2021-01-15 20:24 UTC, mariano-aguero approved these changes

2021-01-15 20:33 UTC, merged